### ISSUE TITLE
Receipt's blockhash is legacy_cita_blockhash

### ISSUE THREAD

**Issue by Pencil-Yao** [cita-cloud/executor_evm#17]
Due to evm have legacy_cita_chain, which the block hash from. So it's a error field for using.

**Comment by Pencil-Yao** [comment]
对EVM的数据库进行进一步缩减，将区块数据，交易数据的存储都依赖于`storage`微服务，本身仅存储状态数据+receipt数据+其他EVM相关数据

**Comment by rink1969** [comment]
表象问题，交易回执里的block hash 跟 直接get block返回的block hash不一样。

**Comment by Pencil-Yao** [comment]
https://github.com/cita-cloud/executor_evm/pull/46
